### ISSUE TITLE
win 怎么带参数打开软件

### ISSUE THREAD

**Issue by JackBome** [gpmn/coinex_robot#1]
win 怎么带参数打开软件

**Comment by gpmn** [comment]
windows用cmd.exe跑：
cd 到程序所在的目录
robot_win.exe -id XXXXXXXXXXXXX -key YYYYYYYYYYYYYYY -discount 0.001 -lsym ONE -rsym USDT     -unit 30 -volignore 10 -volin 3000.0 -volout 50000.0 -interval 100 -diff 0.1 -exchange bigone

或者在程序目录手写一个批处理run.bat，把上面这行内容编辑进去，运行批处理即可。

**Comment by JackBome** [comment]
谢谢

**Comment by JackBome** [comment]
新平台 coinbig.com 了解一下
